language: cpp
compiler: gcc
before_install:
  - sudo apt-get update
  - sudo apt-get install -y libgdal1h libgdal-dev libqt4-dev python-qt4-dev
script:
  - mkdir build
  - cd build
  - cmake ..
  - make

