language: cpp
compiler: gcc
before-install:
  - sudo apt-get update
  - sudo apt-get install -y libgdal-dev libqt4-dev
script:
  - mkdir build
  - cd build
  - cmake -DGDAL_CONFIG=/usr/bin/gdal-config ..
  - make

