language: cpp
compiler: gcc
before-install:
  - sudo apt-get update
  - sudo apt-get install -y libgdal-dev libqt4-dev
script:
  - sudo apt-get install -y libgdal-dev
  - mkdir build
  - cd build
  - cmake ..
  - make

