language: cpp
compiler: gcc
before_install:
  - sudo apt-get update
  - sudo apt-get install -y libgdal1h libgdal-dev libproj-dev libgsl0-dev libqscintilla2-dev libspatialindex-dev libqt4-dev libqwt-dev python-qt4 python-qt4-dev pyqt4-dev-tools
script:
  - mkdir build
  - cd build
  - cmake ..
  - make

